language: python
python:
  - " 3.8.5"

# to be able to use Docker images
services:
  - docker

script:
  - docker pull bleekerlab/snakemake_rnaseq:0.3.2
  - docker run -v $PWD:/home/snakemake bleekerlab/snakemake_rnaseq:0.3.2 -n 