language: python
python:
  - " 3.8.5"

# to be able to use Docker images
services:
  - docker

before_install:
  - docker pull bleekerlab/snakemake_rnaseq:0.3.2

script:
  - docker run -p $PWD:/home/snakemake bleekerlab/snakemake_rnaseq:0.3.2 -n 