
units: data/samples.tsv        # Complete the tab sep value file with the path to the files and their conditions

### Definition of the path Snakemake has to create
working_dir: "temp/"
result_dir: "results/"

### Genome and annotations
refs:
  genome:
        ftp://ftp.solgenomics.net/genomes/Petunia_axillaris/assembly/Petunia_axillaris_v1.6.2_genome.fasta
  proteins_fasta:
        "ftp://ftp.solgenomics.net/genomes/Petunia_axillaris/annotation/Petunia_axillaris_v1.6.2_proteins.fasta"
  transcriptome_gtf:
        "ftp://ftp.solgenomics.net/genomes/Petunia_axillaris/annotation/Petunia_axillaris_v1.6.2_gene_models.gff"

### Software parameters
trimmomatic:
  adapters: "adapters.fasta"
  seedMisMatches: '2'
  palindromeClipTreshold: '30'
  simpleClipThreshold: '10'
  LeadMinTrimQual: '3'
  TrailMinTrimQual: '3'
  windowSize: '4'
  avgMinQual: '15'
  minReadLength: '40'
  phred: "-phred33" # phred: for illumina >1.8 the quality score are encoded by phred33

blast:
  evalue     : "1e-10"
  outFmt     : "6 qseqid evalue length mismatch salltitles"   # 6 for tab separeted file.
  maxTargets : "1"

deseq2:
  maxfraction : '0.7'

filter_for_plots:
  minimum_reads      : '100'       # genes in wich the sum of reads of all samples is less then this value will be excluded.
  minimum_foldchange : '2'         # genes of wich the log2foldchange between all combinations of conditions is smaller then this value will be excluded
  maximum_pvalue     : '0.05'      # genes of wich the adjusted p-value between all combinations of conditions is more then this value will be excluded
  average_samples    : 'yes'       # if "yes", samples within each of the conditions will be averaged, if not the sample values will be outputted

make_plots:
  method_of_clustering : 'pam'   # options are hierchical, kmean and fuzzy_kmean
  opt_clust_number     : 'average_silhouette_width'        # options for hierchical are: fixed, height, dynamic options for (fuzzy-)kmean are: fixed, average_silhouette_width, calinsky_criterion, gap_statistic or affinity_propogation.
  number_of_clusters   : '5'              # to be used when opt_clusts_number = fixed any integer greater than 1
  height_in_dendrogram : '1.5'            # to be used when opt_clusts_number = height number between 0.0 and 2.0 (depents on gene dendrogram)
  colour_of_heatmap    : 'c("white","green","green4","violet","purple")'  # 2 or more colours from list in R "colors()" also used al lot: c("green", "black", "red")
  membership_min       : '0.2'            # can be used when method_of_clustering = fuzzy_kmean
